services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ems-network

volumes:
  redis_data:

networks:
  ems-network:
    driver: bridge
